name: QA Automation
on:
  push:
    branches:
      - 'main'
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Trigger Jenkins Pipeline with Crumb
      env:
        JENKINS_URL: https://9c60-103-167-176-239.ngrok-free.app/
        JENKINS_CRUMB_URL: https://9c60-103-167-176-239.ngrok-free.app/crumbIssuer/api/json
        JENKINS_USER: admin
        JENKINS_TOKEN: bf0ca22f35774571aa00714e200bd3d7
      run: |
        CRUMB=$(curl -s "$JENKINS_CRUMB_URL" \
          --user $JENKINS_USER:$JENKINS_TOKEN | jq -r '.crumb')

        # Trigger the Jenkins job with the Crumb
        curl -X POST "$JENKINS_URL" \
          --user $JENKINS_USER:$JENKINS_TOKEN \
          -H "Jenkins-Crumb:$CRUMB" 


      # - name: "Trigger Jenkins job"
      #   id: trigger-job
      #   uses: umutcolak/jenkins-trigger-job@main
      #   with:
      #     jenkins-url: https://0ed5-103-167-176-239.ngrok-free.app/
      #     user: admin
      #     jenkins-token: bf0ca22f35774571aa00714e200bd3d7
      #     job-name: test
      #     job-params: '{}'
      #     crumb: b471a76279623f6297a77aa0772231404e7e9f99c6abecc85d617de2e1a80274
      
      # - name: "Get Build Number"
      #   id: get-build-number
      #   run: |
      #     # Fetch the job details to get the latest build number
      #     JOB_API_RESPONSE=$(curl -s -u admin:bf0ca22f35774571aa00714e200bd3d7 \
      #       https://0ed5-103-167-176-239.ngrok-free.app/job/test/api/json)
      #     echo "API Response: $JOB_API_RESPONSE"

      #     # Extract the latest build number from the job's API response
      #     LAST_BUILD_NUMBER=$(echo $JOB_API_RESPONSE | jq -r '.lastBuild.number')

      #     if [ "$LAST_BUILD_NUMBER" == "null" ]; then
      #       echo "Failed to fetch the last build number"
      #       exit 1
      #     fi

      #     echo "Last Build Number: $LAST_BUILD_NUMBER"
      #     echo "BUILD_NUMBER=$LAST_BUILD_NUMBER" >> $GITHUB_ENV
          
      # - name: "Wait for Jenkins Build to Complete"
      #   id: wait-for-build
      #   run: |
      #     BUILD_URL="https://0ed5-103-167-176-239.ngrok-free.app/job/test/$BUILD_NUMBER"
      #     echo "Build URL: $BUILD_URL"
      #     # Poll the build status until it's completed
      #     while true; do
      #       BUILD_STATUS=$(curl -s -u admin:bf0ca22f35774571aa00714e200bd3d7 \
      #         ${BUILD_URL}/api/json | jq -r '.building')
      #       if [ "$BUILD_STATUS" == "false" ]; then
      #         break
      #       fi
      #       echo "Build is still running..."
      #       sleep 10
      #     done
      #     BUILD_RESULT=$(curl -s -u admin:bf0ca22f35774571aa00714e200bd3d7 \
      #       ${BUILD_URL}/api/json | jq -r '.result')
      #     echo "BUILD_RESULT=$BUILD_RESULT" >> $GITHUB_ENV


      #     echo "BUILD_RESULT=$BUILD_RESULT" >> $GITHUB_ENV

      # # - name: "Print Build Result"
      # #   run: echo "Jenkins Build Result: ${{ env.BUILD_RESULT }}"
