name: Jenkins
on:
  push:
    branches:
      - 'develop'
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Install jq
      run: sudo apt-get install -y jq

    - name: Trigger Jenkins Pipeline with Crumb
      env:
        JENKINS_URL: https://9c60-103-167-176-239.ngrok-free.app/job/Test/buildWithParameters
        JENKINS_CRUMB_URL: https://9c60-103-167-176-239.ngrok-free.app/crumbIssuer/api/json
        JENKINS_USER: admin
        JENKINS_TOKEN: bf0ca22f35774571aa00714e200bd3d7
      run: |
        # Fetch the Jenkins Crumb dynamically
        CRUMB=$(curl -s "$JENKINS_CRUMB_URL" \
          --user $JENKINS_USER:$JENKINS_TOKEN | jq -r '.crumb')
        echo $CRUMB
       
        # Ensure CRUMB was successfully fetched
        if [ -z "$CRUMB" ]; then
          echo "Failed to fetch Jenkins Crumb!"
          exit 1
        fi

        # Trigger the Jenkins job with the dynamically fetched Crumb
        curl -X POST "$JENKINS_URL" \
          --user $JENKINS_USER:$JENKINS_TOKEN \
          -H "Jenkins-Crumb:$CRUMB" 

