name: Secure Password Input

on:
  workflow_dispatch:
    inputs:
      USER_PASSWORD:
        description: "Enter your input"
        required: true
        default: "default_value"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Ask for Password
      id: get-password
      run: |
        echo "Please enter your password:"
        read -s USER_PASSWORD
        echo "::add-mask::$USER_PASSWORD"
        echo "user_password=$USER_PASSWORD" >> $GITHUB_ENV

    - name: Use Password
      run: |
        echo "Your password is stored securely."
        # Use the password for any task, it won't be printed
        echo "Password: ${{ env.USER_PASSWORD }}"
