name: Upload folder to SharePoint

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # - name: Set up Node.js (if needed)
      #   uses: actions/setup-node@v3
      #   with:
      #     node-version: '16'

      # - name: Install dependencies (if needed)
      #   run: npm install

      # - name: Build project (if needed)
      #   run: npm run build

      - name: Zip the folder
        run: zip -r output.zip ${{ github.workspace }}/Ansible_Learning

      - name: Upload to SharePoint
        env:
          SHAREPOINT_URL: ${{ secrets.SHAREPOINT_URL }}
          SHAREPOINT_USERNAME: ${{ secrets.SHAREPOINT_USERNAME }}
          SHAREPOINT_PASSWORD: ${{ secrets.SHAREPOINT_PASSWORD }}
        run: |
          FILE_PATH="output.zip"
          SHAREPOINT_DEST_PATH="/Shared Documents/output.zip"
          curl -k -X POST -H "Content-Type: multipart/form-data" \
          --user "$SHAREPOINT_USERNAME:$SHAREPOINT_PASSWORD" \
          -F "file=@${FILE_PATH}" \
          "${SHAREPOINT_URL}/_api/web/GetFolderByServerRelativeUrl('${SHAREPOINT_DEST_PATH%/*}')/Files/add(url='${SHAREPOINT_DEST_PATH##*/}', overwrite=true)"
