name: Upload folder to SharePoint

on:
  workflow_dispatch:
    inputs:
      URL:
        description: 'Enter the URL'
        required: true
        type: string
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Zip the folder
        run: zip -r output.zip ${{ github.workspace }}

      - name: run the cmd
        run: |
          ls -ltr
          pwd
     
      - name: setting SHAREPOINT_URL
        env:
          SHAREPOINT_URL: "${{ github.event.inputs.URL }}"
        run: echo "$SHAREPOINT_URL"
        
      - name: Upload to SharePoint
        env:
          SHAREPOINT_URL: "${{ github.event.inputs.URL }}"
          SHAREPOINT_USERNAME: "${{ secrets.SHAREPOINT_USERNAME }}"
          SHAREPOINT_PASSWORD: "${{ secrets.SHAREPOINT_PASSWORD }}"
        run: |
          FILE_PATH="${{ github.workspace }}/output.zip"
          SHAREPOINT_DEST_PATH="/Shared Documents/output.zip"
          curl -k -X POST -H "Content-Type: multipart/form-data" \
          --user "$SHAREPOINT_USERNAME:$SHAREPOINT_PASSWORD" \
          -F "file=@${FILE_PATH}" \
          "${SHAREPOINT_URL}/_api/web/GetFolderByServerRelativeUrl('${SHAREPOINT_DEST_PATH%/*}')/Files/add(url='${SHAREPOINT_DEST_PATH##*/}', overwrite=true)"
