name: QA Automation
on:
  push:
    branches:
      - 'main'
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: "Trigger Jenkins job"
        id: trigger-job
        run: |
          RESPONSE=$(curl -s -u admin:bf0ca22f35774571aa00714e200bd3d7 \
            -X POST https://0ed5-103-167-176-239.ngrok-free.app/job/test/build?token=bf0ca22f35774571aa00714e200bd3d7 \
            -i)
          
          # Print the response headers for debugging
          echo "$RESPONSE"

          # Extract the queueId from the Location header
          QUEUE_ID=$(echo "$RESPONSE" | grep -oP '(?<=Location: .*/queue/item/)\d+')

          if [ -z "$QUEUE_ID" ]; then
            echo "Failed to retrieve queue ID. Response headers: $RESPONSE"
            exit 1
          fi

          echo "Queue ID: $QUEUE_ID"
          echo "QUEUE_ID=$QUEUE_ID" >> $GITHUB_ENV

      - name: "Get Build Number"
        id: get-build-number
        run: |
          while true; do
            BUILD_NUMBER=$(curl -s -u admin:bf0ca22f35774571aa00714e200bd3d7 \
              https://0ed5-103-167-176-239.ngrok-free.app/queue/item/${{ env.QUEUE_ID }}/api/json | jq -r '.executable.number')

            if [ "$BUILD_NUMBER" != "null" ]; then
              echo "Build Number: $BUILD_NUMBER"
              echo "BUILD_NUMBER=$BUILD_NUMBER" >> $GITHUB_ENV
              break
            fi
            echo "Waiting for the build to start..."
            sleep 5
          done

      - name: "Wait for Jenkins Build to Complete"
        id: wait-for-build
        run: |
          BUILD_URL="https://0ed5-103-167-176-239.ngrok-free.app/job/test/$BUILD_NUMBER"
          echo "Build URL:
