name: QA Automation
on:
  push:
    branches:
      - 'main'
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: "Trigger Jenkins job"
        id: trigger-job
        uses: umutcolak/jenkins-trigger-job@main
        with:
          jenkins-url: https://0ed5-103-167-176-239.ngrok-free.app/
          user: admin
          jenkins-token: bf0ca22f35774571aa00714e200bd3d7
          job-name: test
          job-params: '{}'
          crumb: b471a76279623f6297a77aa0772231404e7e9f99c6abecc85d617de2e1a80274

      - name: "Get Build Number"
        id: get-build-number
        run: |
          # Fetch the queue item and get the executable (build number)
          QUEUE_URL=$(curl -s -u admin:bf0ca22f35774571aa00714e200bd3d7 \
            https://0ed5-103-167-176-239.ngrok-free.app/job/test/api/json | jq -r '.lastBuild.queueId')
          echo "Queue ID: $QUEUE_URL"

          while true; do
            BUILD_NUMBER=$(curl -s -u admin:bf0ca22f35774571aa00714e200bd3d7 \
              https://0ed5-103-167-176-239.ngrok-free.app/queue/item/$QUEUE_URL/api/json | jq -r '.executable.number')

            if [ "$BUILD_NUMBER" != "null" ]; then
              echo "Build Number: $BUILD_NUMBER"
              echo "BUILD_NUMBER=$BUILD_NUMBER" >> $GITHUB_ENV
              break
            fi
            echo "Waiting for the build to start..."
            sleep 5
          done

      - name: "Wait for Jenkins Build to Complete"
        id: wait-for-build
        run: |
          BUILD_URL="https://0ed5-103-167-176-239.ngrok-free.app/job/test/$BUILD_NUMBER"
          echo "Build URL: $BUILD_URL"

          # Poll the build status until it's completed
          while true; do
            BUILD_STATUS=$(curl -s -u admin:bf0ca22f35774571aa00714e200bd3d7 \
              ${BUILD_URL}/api/json | jq -r '.building')

            if [ "$BUILD_STATUS" == "false" ]; then
              break
            fi
            echo "Build is still running..."
            sleep 10
          done

          BUILD_RESULT=$(curl -s -u admin:bf0ca22f35774571aa00714e200bd3d7 \
            ${BUILD_URL}/api/json | jq -r '.result')

          echo "BUILD_RESULT=$BUILD_RESULT" >> $GITHUB_ENV

      # - name: "Print Build Result"
      #   run: echo "Jenkins Build Result: ${{ env.BUILD_RESULT }}"
