name: QA Automation
on:
  push:
    branches:
      - 'main'
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: "Trigger Jenkins job"
        id: trigger-job
        run: |
          RESPONSE=$(curl -s -u admin:bf0ca22f35774571aa00714e200bd3d7 \
            -X POST https://0ed5-103-167-176-239.ngrok-free.app/job/test/build?token=bf0ca22f35774571aa00714e200bd3d7 \
            -i)
          QUEUE_ID=$(echo "$RESPONSE" | grep -oP '(?<=Location: .*/queue/item/)\d+')
          if [ -z "$QUEUE_ID" ]; then
            echo "Failed to retrieve queue ID"
            exit 1
          fi
          echo "QUEUE_ID=$QUEUE_ID" >> $GITHUB_ENV
          echo "Queue ID: $QUEUE_ID"

      - name: "Get Build Number"
        id: get-build-number
        run: |
          while true; do
            BUILD_NUMBER=$(curl -s -u admin:bf0ca22f35774571aa00714e200bd3d7 \
              https://0ed5-103-167-176-239.ngrok-free.app/queue/item/${{ env.QUEUE_ID }}/api/json | jq -r '.executable.number')

            if [ "$BUILD_NUMBER" != "null" ]; then
              echo "Build Number: $BUILD_NUMBER"
              echo "BUILD_NUMBER=$BUILD_NUMBER" >> $GITHUB_ENV
              break
            fi
            echo "Waiting for the build to start..."
            sleep 5
          done

      - name: "Wait for Jenkins Build to Complete"
        id: wait-for-build
        run: |
          BUILD_URL="https://0ed5-103-167-176-239.ngrok-free.app/job/test/$BUILD_NUMBER"
          echo "Build URL: $BUILD_URL"

          while true; do
            BUILD_STATUS=$(curl -s -u admin:bf0ca22f35774571aa00714e200bd3d7 \
              ${BUILD_URL}/api/json | jq -r '.building')

            if [ "$BUILD_STATUS" == "false" ]; then
              break
            fi
            echo "Build is still running..."
            sleep 10
          done

          BUILD_RESULT=$(curl -s -u admin:bf0ca22f35774571aa00714e200bd3d7 \
            ${BUILD_URL}/api/json | jq -r '.result')

          echo "BUILD_RESULT=$BUILD_RESULT" >> $GITHUB_ENV

      # - name: "Print Build Result"
      #   run: echo "Jenkins Build Result: ${{ env.BUILD_RESULT }}"
